name: Release and publish

on:
  workflow_run:
    workflows: [ "MacroDensity CI" ]
    branches: [ main ]
    types:
      - completed  # only release when tests have passed

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    # only run when tests have passed (or manually triggered)

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools setuptools_scm wheel
          pip install -e .[tests]

      - name: Build packages
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TWINE_PASSWORD }}

      - name: Generate release info
        run: |
          awk 'BEGIN {p = 0} {a = 0 }; /^v\d*.\d*.\d*./ { p += 1; a = 1}; p + a == 1 { print } ' CHANGELOG.rst | sed -e '1,1d' | sed  -e '/./,$!d' -e :a -e '/^\n*$/{$d;N;ba' -e '}' > release_info.txt
          echo "version=$(grep version setup.py | awk -F\" '{print $2}')" >> $GITHUB_ENV

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          release_name: ${{ env.version }}
          body_path: release_info.txt
          draft: false
          prerelease: false
